package com.elliott.supervideoplayer.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.support.annotation.NonNull;

/**
 * Entity mapped to table VIDEO_BEAN.
 */
public class VideoBean implements Comparable {
    private Long id;
    /** Not-null value. */
    private String VideoName;
    private String VideoLink;
    private String thumbnailPath;
    private String totalsize;
    private String totalduration;
    private Integer type;
    private long time;

    public VideoBean() {
    }

    public VideoBean(Long id) {
        this.id = id;
    }

    public VideoBean(Long id, String VideoName, String VideoLink,
                     String thumbnailPath, String totalsize, String totalduration,
                     Integer type, long time) {
        this.id = id;
        this.VideoName = VideoName;
        this.VideoLink = VideoLink;
        this.thumbnailPath = thumbnailPath;
        this.totalsize = totalsize;
        this.totalduration = totalduration;
        this.type = type;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getVideoName() {
        return VideoName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoName(String VideoName) {
        this.VideoName = VideoName;
    }

    public String getVideoLink() {
        return VideoLink;
    }

    public void setVideoLink(String VideoLink) {
        this.VideoLink = VideoLink;
    }

    public String getThumbnailPath() {
        return thumbnailPath;
    }

    public void setThumbnailPath(String thumbnailPath) {
        this.thumbnailPath = thumbnailPath;
    }

    public String getTotalsize() {
        return totalsize;
    }

    public void setTotalsize(String totalsize) {
        this.totalsize = totalsize;
    }

    public String getTotalduration() {
        return totalduration;
    }

    public void setTotalduration(String totalduration) {
        this.totalduration = totalduration;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    @Override
    public int compareTo(@NonNull Object o) {
        long time = ((VideoBean) o).getTime();
        if (time < this.time) {
            return -1;
        } else if (time == this.time) {
            return 0;
        } else {
            return 1;
        }
    }
}
